services:
  - name: santos3-back
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: autorack.proxy.rlwy.net
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: rXVnuzXHgYQquNGRoiSiKvWKXnfKHARY
      - key: DB_NAME
        value: railway
      - key: DB_DIALECT
        value: mysql
      - key: DB_PORT
        value: 57928
    healthCheckPath: /health
    plan: free
    autoDeploy: true
