services:
  - name: santos3-back
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: mysql-host
      - key: DB_USER
        value: seu-usuario
      - key: DB_PASSWORD
        value: sua-senha
      - key: DB_NAME
        value: nome-do-banco
    healthCheckPath: /health
    plan: free
    autoDeploy: true
